version: '3.8'

services:
  frontend:
    container_name: frontendflask
    build:
      context: ./frontend-flask
    ports:
      - "5000:5000"
    environment:
      - API_SERVER_URL=http://backend:8080
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    networks:
      - app-network
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: password
      DB_NAME: shoppingcart
      DB_SSLMODE: disable
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shoppingcart
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
